trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Maven@3
  inputs:
    goals: 'clean package'
    options: '-DskipTests'
    mavenPomFile: 'pom.xml'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    mavenOptions: '-Xmx3072m'
    sqAnalysisEnabled: false
    checkstyleAnalysisEnabled: false
    pmdAnalysisEnabled: false
    findbugsAnalysisEnabled: false
